collective/collective.exportimport

setup.py, src/collective/exportimport/import_content.py
=> Experiment with ijson to support large files

CHANGES.rst, src/collective/exportimport/import_content.py, src/collective/exportimport/templates/import_content.pt, src/collective/exportimport/tests/test_import.py
We look in the same places that the zexp import code looks, which means the import directory in the client home and instance home.
This builds on the branch my PR #13 which introduces tests.
TODO: actually add a test for this new option, which is why I mark this as a Draft PR.
But it works for me when I try it manually (Plone 5.2, Py 3.8).
=> Add option to import file from server.

.github/workflows/tests.yml, CHANGES.rst, buildout.cfg, setup.py, src/collective/exportimport/configure.zcml, src/collective/exportimport/export_other.py, src/collective/exportimport/import_content.py, src/collective/exportimport/templates/import_content.pt, src/collective/exportimport/testing.py, src/collective/exportimport/tests/test_export.py, src/collective/exportimport/tests/test_import.py, src/collective/exportimport/tests/test_setup.py, tox.ini
I added initial tests for exporting and importing one document, and for exporting members.
Locally you can run `tox -p auto` to run the tests for the two environments I have defined: Plone 5.2 on Python 2.7 and on 3.8.
On 2.7 I skip the import content test for the moment, because it fails with a date format error. See comment in the code. I think we know about that error already.
I would want to run the export tests on 4.3 as well, but that is left as an exercise for later.
This PR also contains a few small fixes that I discovered while getting the buildout and instance running (for example include CMFCore so we can use the Manage Portal permission in zcml) and the tests running (mainly a possible json/bytes error while exporting the test member).
Not perfect, but it is a start.
=> Basic test setup with tox and GitHub Actions

base.cfg, buildout.cfg, src/collective/exportimport/tests/test_import.py, test-4.3.x.cfg, test-5.0.x.cfg, test-5.1.x.cfg, test-5.2.x.cfg, tox.ini
The import tests are only supported on Plone 5.2 Python 3.7/3.8.
On Python 3.6 and lower I skip the import tests because of the datetime problem from issue #10.
=> Test on more Plone and Python versions.

base.cfg, buildout.cfg, src/collective/exportimport/tests/test_export.py, src/collective/exportimport/tests/test_import.py, src/collective/exportimport/tests/test_setup.py, test-4.3.x.cfg, test-5.0.x.cfg, test-5.1.x.cfg, test-5.2.x.cfg, tox.ini
This builds on and includes the small changes from my PR #16, for testing on more Plone/Python versions.
=> Add export and import tests for default pages and ordering

CHANGES.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/export_content.py
You get this for example in Plone 4.3 with only collective.easyform.
Partial traceback when visiting the export-content page:
```
Module collective.exportimport.export_content, line 218, in portal_types
AttributeError: 'NoneType' object has no attribute 'providedBy'
```
That is [this line](https://github.com/collective/collective.exportimport/blob/134c18da5d32bc11a986db87d5c458eea7ac2684/src/collective/exportimport/export_content.py#L218).
Also, registered the [`relationvalue_converter_uuid`](https://github.com/collective/collective.exportimport/blob/134c18da5d32bc11a986db87d5c458eea7ac2684/src/collective/exportimport/export_content.py#L344-L346) serializer/adapter. It had an `@adapter` and `@implementer` but no zcml was registering it.
=> Fix use in Plone 4.3 with dexterity but without z3c.relationfield.

CHANGES.rst, setup.py
The package now supports installation with pip (`pip install collective.exportimport`) for the following Python versions:
- Python 2.7.x
- Python >= 3.7.x
Fixes #36
=> Fix installation using pip.

CHANGES.rst, src/collective/exportimport/export_content.py
This avoids memory ballooning to the size of the exported file.
=> Export content and write to file using a generator/yield. 

.github/workflows/tests.yml, base.cfg, constraints.txt, constraints_plone52.txt, requirements.txt, setup.py, src/collective/exportimport/tests/test_export.py, src/collective/exportimport/tests/test_import.py, test-5.0.x.cfg
All tox/GHA environments were testing Plone 5.2.
Looks like I made the mistake in May.
Some tests on 5.1 and lower fail now... Might just be differences in how to call the zope test browser.
=> Use the correct Plone versions when testing.

CHANGES.rst, src/collective/exportimport/import_content.py, src/collective/exportimport/tests/test_import.py
This fixes errors like this:
zExceptions.BadRequest: The id "plone" is reserved.
I found this when exporting Folders and Documents using the `support_trees` branch, and then importing them in a fresh site. Some of the Documents were not in Folders, but in a different portal_type, so a folder structure was missing.
=> Fixed creating missing folder structure.

CHANGES.rst, README.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/export_content.py, src/collective/exportimport/import_content.py, src/collective/exportimport/interfaces.py, src/collective/exportimport/serializer.py, src/collective/exportimport/templates/export_content.pt, src/collective/exportimport/tests/test_import.py
This adapts Philips code from issue #17 for exporting and import blobs by just their path.
Works for me in a large export/import from 4.3 to 5.2.
I tried adding a test, see current last commit, but the DemoStorage in the functional test seems to miss the `fshelper` which would be needed to find the actual blobstorage.
=> Support blob paths

CHANGES.rst, src/collective/exportimport/config.py, src/collective/exportimport/export_content.py, src/collective/exportimport/import_content.py, src/collective/exportimport/tests/test_import.py
When set, this is used for storing an export file and getting an import file.
This is useful for sharing content between multiple Plone Sites on the same server.
=> Read environment variable COLLECTIVE_EXPORTIMPORT_CENTRAL_DIRECTORY.

CHANGES.rst, src/collective/exportimport/import_content.py, src/collective/exportimport/tests/test_import.py
In general, cleanup parent paths when in development on localhost.
See explanation in `get_parent_as_container` method.
Also, in test_import_content_document test what happens when importing twice.
Biggest thing I wanted to check, because I had my doubts:
do we get the original UID on the first import, and a new UID on the second?
Answer: yes.
=> Prevent creating content in a different Plone Site in the same database.

setup.cfg, setup.py
I noticed that on the main branch, the Plone [4.3 tests are broken](https://github.com/collective/collective.exportimport/runs/3766167980), trying to install `jsonschema`.
Version 4 of jsonschema was released yesterday, and it is Py3-only.
I don't know who pulls in this dependency.
jsonschema itself depends on six >= 1.11.0.
Since Plone 5.1 pins six to 1.10.0, we need to pin this as well.
=> On Py 2.7, pin jsonschema to last compatible version.

src/collective/exportimport/export_other.py
I already fixed this half a year or so ago in export_content.py, but now a similar problem is there in export_other.py.
I tried creating an extra tox env for this, with Products.CMFPlone 4.3 instead of Plone,
but z3c.relationfield was pulled in anyway, probably via a test dependency.
=> Fixed ImportError when z3c.relationfield is missing.

src/collective/exportimport/export_content.py, src/collective/exportimport/import_content.py, src/collective/exportimport/tests/test_import.py
=> export and import constrains

src/collective/exportimport/export_content.py
Given the logging settings, errors were being swallowed and this was impossible to debug.
=> Log exception when failing to export content

src/collective/exportimport/fix_html.py, src/collective/exportimport/tests/test_fix_html.py
Merry Christmas!  This PR simplifies the HTML tag fixer, and also ensures that the `<source>` tags are `resolveuid`'d too.
Counterpart of https://github.com/plone/plone.app.linkintegrity/pull/83
=> Fix the <source> / <iframe> tags too, and unify tag fix handling.

src/collective/exportimport/fix_html.py, src/collective/exportimport/tests/test_fix_html.py
This time we include a test to ensure we don't hit this condition.
=> Ensure that links with spaces (arguably valid) do not get double-appended as a result of srcset processing.

CHANGES.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/interfaces.py, src/collective/exportimport/serializer.py
Exporting a PloneFormGen all the TALES override expressions are converted in their respective evaluated expressions because of restapi `DefaultFieldSerializer` that uses default accessor(). Then Deserializing the json yields to a conversion error: it expects strings but finds all kind of type of values returned by the tales.
With this PR, tales expression are kept in their raw string value into the Json so the defaultdeserializer can do the job.
=> Fixes TALES serializer in raw text instead of evaluated expression.

src/collective/exportimport/export_other.py, src/collective/exportimport/import_other.py, src/collective/exportimport/tests/test_export.py
The old version did not account for default_pages that changed teir id during exportimport and failed to find the default page for translated items.
=> Use catalog and uuids to export/import default_page

README.rst, src/collective/exportimport/export_content.py, src/collective/exportimport/import_content.py, src/collective/exportimport/templates/export_content.pt, src/collective/exportimport/templates/import_content.pt, src/collective/exportimport/tests/test_export.py, src/collective/exportimport/tests/test_import.py
=> Export and import content revisions

CHANGES.rst, src/collective/exportimport/export_content.py, src/collective/exportimport/import_content.py, src/collective/exportimport/tests/test_import.py
I don't know why I did not have this idea earlier. Using the parent UID makes it much easier to deal with cases where content moves around during migrations (e.g. when migrating to plone.app.multilingual).
Also this moves the various export-hooks into update_export_data for readability.
=> Use parent uuid to find the container to import

CHANGES.rst, src/collective/exportimport/export_other.py
In our case with Plone 4.3 and p.a.multilingual 1.2.x, I needed to add this, otherwise no translations where exported.
But I don't know if it's just one edge case or is a generic one. 
It requires further testing in old p.a.multilingual versions.
=> use Language=all when exporting translations for plone.app.multilingual 1.x

CHANGES.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/import_other.py
Fixes #144 
This way the endpoint is registered only when `ITranslationManager` exists in p.a.multilingual, what happens in versions >= 2.
This way this addon can be used in Plone 4.3.x sites with p.a.multilingual 1.2.x. In such cases we just want to export the content, so we should not bother about not being able to import the translations.
=> be more specific in the zcml condition

src/collective/exportimport/import_content.py
log, rather than fail, on errors in setLocallyAllowedTypes and setImmediatelyAddableTypes (typically, a type that does not exist).
=> log, rather than fail, on errors in import_constrains

test-5.2.x.cfg
Was failing with:
```
Version and requirements information containing charset-normalizer:
[versions] constraint on charset-normalizer: 2.1.1
Requirement of requests: charset-normalizer~=2.0.0
While:
Installing test.
```
See, e.g. https://github.com/collective/collective.exportimport/actions/runs/4086004109/jobs/7044735464
=> Fix the build on Plone 5.2/Python 3.6

requirements.txt
setuptools 67 is too strict.
See test failure here:
https://github.com/collective/collective.exportimport/actions/runs/4135262761/jobs/7147478436#step:9:55 Products.CMFPlone 5.2.11 depends on plone.app.contentmenu>=1.1.6dev-r22380 and this is an illegal requirement with setuptools 67. I will fix that for the next Plone version.
=> CI: pin setuptools lower than 67.

CHANGES.rst, src/collective/exportimport/import_content.py
When trying to import content into Volto that does not have a parent, the following exception occurs:
```
plone.api.exc.InvalidParameterError: Cannot add a 'Folder' object to the container.
Allowed types are:
Document
Event
File
Image
Link
News Item
Disallowed subobject type: Folder
```
This PR checks whether the root is folderish (as it is with Volto) and uses the `Page` type instead.
## Future
It would be nice if this was more generic (i.e. the type the parent should be was stored in the export), but this would likely have a big impact on the JSON size
=> Handle Volto not using 'Folder' when trying to create missing parents

CHANGES.rst, src/collective/exportimport/import_content.py
This allows the hooks to have access to the item UUID. Fix #185.
One item of concern: I have now also moved the check if the 'set' uid matches the uid on the import item dict.   
>             if uuid != item.get("UID"):
>                item["UID"] = uuid
In theory this causes the custom dict hooks to no longer have access to that uuid or override this action.  Should the condition be moved after the custom dict hooks calls? 
The original commit for this condiation had this comment: " Support importing content without a UUID (e.g. for importing from an external source"
=> Import: run set_uuid method before we call custom hooks

CHANGES.rst, src/collective/exportimport/import_other.py
This was a critical bug when importing groups. The json for exported groups has the data `group["groups"]`. That is a list of groups to which the group belongs to. This data need not be used during import and is rather for information and debugging. `group["principals"]` is a list of all members of the group (be they groups or users).
=> Do not import groups that a group belongs to as members of the new group.

CHANGES.rst, src/collective/exportimport/serializer.py
to take care of connection wrapped in a temp storage
=> Use db.storage instead of connection._storage

CHANGES.rst, src/collective/exportimport/import_other.py
Otherwise only one portlet will be successfully imported for each location and column as all remaining ones are placed into the wrong `mapping`.
This fixes 6b4bdc50.
=> fix: don't re-use `mapping` variable

src/collective/exportimport/import_content.py
context: Import items transaction failed quietly when importing a lot of files/images from blobstorage. This was solved by adding a transaction savepoint for every imported 100 items
=> add savepoint

src/collective/exportimport/export_content.py, src/collective/exportimport/templates/export_content.pt
This adds a new form field on `@@export_content` "write_errors" which turns on a list of unexported paths at the end of a json export.
When 'write_errors' is set to a true value, the export appends the list like so:
```
[{
"@id": "http://localhost:8081/RFA/english/item1",
"@type": "news_item",
"UID": "34b9faa0dbe648b6826174abc4ff85c1",
... <snip>
},
{
"@id": "http://localhost:8081/RFA/english/item2",
"@type": "news_item",
"UID": "34b9faa0dbe648b6826174abc4ff85c2",
... <snip>
},{
"@id": "http://localhost:8081/RFA/english/item3",
"@type": "news_item",
"UID": "34b9faa0dbe648b6826174abc4ff85c3",
... <snip>
},{
"unexported_paths": [
{
"path": "http://localhost:8081/RFA/english/news/story-slideshow-05232023120021.html",
"message": "Error exporting …
```
=> 208 better reporting of failed exported objects

CHANGES.rst, setup.py, src/collective/exportimport/import_content.py
Avoid parsing JSON twice and dumping once for each content object.
The only deserializer that does not support data as keyword argument is the portal deserializer.
For all other content items, dumping to JSON to setup the request before loading from JSON in the `json_body` function is really overkill as the item has already been parsed when loaded from file.
=> Better support for portal import.

CHANGES.rst, src/collective/exportimport/export_other.py, src/collective/exportimport/import_other.py
context: migration only checked on uid, which left out the portal root. (and the portlets on the root weren't migrated)
=> migrate portlets on site root

CHANGES.rst, src/collective/exportimport/export_content.py
When exporting into separate JSON files write also the error in a separate errors.json file. This fixes an error at the end of the export and no errors being written.
=> Fix writing error-file with separate JSON file export.

CHANGES.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/export_topic.py
Sometimes you want to export a collection of items from an old Plone4 website and import them all in one folder. This way you can add a ATTopic with a custom query and then call `my-topic/export_content`.
=> ATTopic export_content

CHANGES.rst, src/collective/exportimport/import_other.py
=> Add principals to groups that already exist during import

CHANGES.rst, src/collective/exportimport/serializer.py
This is a fix I came up when exporting content where for some unknown reason some quite old Blobs from a project from 2013 were in a broken state.
I got a warning `WARNING OFS.Uninstalled Could not import class 'NamedBlobFile' from module 'zope.app.file.file'` which is related to the broken blobs but I cannot recall via git searches why I'd have used zope.app.file once.
However, this PR fixes my problem. I'm OK if this won't get merged and live in a local branch instead.
=> Try to restore broken blobs when exporting content.

CHANGES.rst, src/collective/exportimport/fix_html.py
This way you can use it in upgrade-steps
e.g:
```python
def upgrade(setup_tool=None):
from collective.exportimport.fix_html import fix_html_in_content_fields
fixers = [text_img_align_fixer]
fix_html_in_content_fields(fixers=fixers, apply_default_fixer=False)
def text_img_align_fixer(text, obj=None):
"""Replace inline-styles for img tags with classes."""
from bs4 import BeautifulSoup
if not text:
return text
replaced_styles = {
"float: left": "image-left",
"float: right": "image-right",
}
soup = BeautifulSoup(text, "html.parser")
for tag in soup.find_all("img"):
styles = tag.get("style", "").split(";")
styles = [i.strip() for i in styles if i.strip()]
if not styles:
continue
new_classes = []
old_classes = tag.get("class", [])
for old, new in replaced_styles.items():
if old in styles: …
```
=> Allow to use fix_html_in_content_fields without applying the default html_fixer

src/collective/exportimport/import_other.py
We have seen values like this when doing an export of a Plone 4 site:
```json
{
"default_page": "index_html", 
"default_page_uuid": null, 
"uuid": "418cd0dd43d7433c9e508679c649a9ff"
}, 
{
"default_page": "index_html", 
"default_page_uuid": null, 
"uuid": "19c24adf7cae434c897285fab5cbf240"
}, 
```
These changes check whether the value in `default_page_uuid` is not None, before searching the item in the catalog.
=> safeguard against empty/None values in default_page_uuid

CHANGES.rst, README.rst, setup.py
When I‌ tried to install this package in Plone 4 it took me some time to get the versions straight. It would have saved me some time if I had read the Plone 4 install section in the README, but I didn't and it is well hidden.
I think having an easy installation experience in Plone 4 with Python 2 is quite important for this package as this is probably a frequent use case.
This PR should fix that out of the box and improve the README a bit, as of the time of this writing. There is a good chance that it will break again, however, for now it does work fine.
/cc @canepan
=> Better Plone 4 / Python 2 compatibility

CHANGES.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/serializer.py
Fixes #147
Use more specific interface INamedBlobFileField for blob files and leave INamedFileField to be base64 encoded even with blob_paths selected
=> Fix AtributeError 'NamedFile' object has no attribute '_blob' when exporting objects with plone.namedfile.file.NamedFile properties

README.rst
rstcheck is used by GitHub to validate README.rst files. See https://github.com/orgs/community/discussions/86715#discussioncomment-8431598. Currently the README.rst does not pass this validation, thus making the README no longer render.
This PR addresses all the validation issues, except for the XML code-blocks. For that, I need some guidance from the maintainers. Semantically XML is the correct language, but HTML passes rstcheck. Should I change the language from XML to HTML?
```console
$ bin/rstcheck imp.rst
imp.rst:347: (ERROR/3) (xml) unbound prefix: line 1, column 0
imp.rst:409: (ERROR/3) (xml) unbound prefix: line 1, column 0
imp.rst:1025: (ERROR/3) (xml) unbound prefix: line 1, column 0
Error! Issues detected.
```
This PR also updates a few outdated links and some minor syntax …
=> Fix failing rstcheck

CHANGES.rst, src/collective/exportimport/export_other.py, src/collective/exportimport/tests/test_export.py
Ignore when a user is a member of group x only because he is in another group that is a member of x
=> Ignore transitive membership of groups 

CHANGES.rst, src/collective/exportimport/configure.zcml, src/collective/exportimport/deserializer.py, src/collective/exportimport/serializer.py
bypass the frontend-specific modifiers when serializing and deserializing blocks
=> Fix migrating bocks 

CHANGES.rst, DEVELOP.rst, requirements_black.txt, src/collective/exportimport/config.py, src/collective/exportimport/export_content.py, src/collective/exportimport/export_other.py, src/collective/exportimport/export_topic.py, src/collective/exportimport/fix_html.py, src/collective/exportimport/import_content.py, src/collective/exportimport/import_other.py, src/collective/exportimport/interfaces.py, src/collective/exportimport/serializer.py, src/collective/exportimport/tests/test_drop_and_include.py, src/collective/exportimport/tests/test_export.py, src/collective/exportimport/tests/test_fix_html.py
I ran black with the default settings. Not sure if the previous run of black had other settings, but the output looks fine.
=> Run python2 compatible black

src/collective/exportimport/serializer.py
When exporting from a CastleCMS site, it turned out namedfile.filename wasn't always defined. Found and fixed by @pbauer, should be integrated in main.
=> fix for exporting from Castle sites, found at Beethovensprint2024

CHANGES.rst, setup.py, src/collective/exportimport/serializer.py
This does the same for `NamedImage` like #236 does for `NamedFile`
=> Fix `AtributeError: 'NamedImage' object has no attribute '_blob'`

CHANGES.rst, requirements.txt, src/collective/exportimport/export_content.py, src/collective/exportimport/templates/export_content.pt, src/collective/exportimport/tests/test_export.py, tox.ini
Fixes issue #247.
Also a fix for 6.1.  The boolean checkboxes in `export_content` were displayed in block:
This is because some change in Barceloneta for 6.1 sets `label input {display: block}`.  I guess this is fine in general, but not here.
Now they are displayed inline again:
=> Fix issue 247, migration was always true.

CHANGES.rst, base.cfg, requirements.txt, src/collective/exportimport/import_other.py
A custom migration may have turned a former container into an item.
=> Fix `AttributeError: __contains__` when checking default-page on non folder

base.cfg, requirements.txt
When I manually return GitHub Actions on the main branch, it currently [fails](https://github.com/collective/collective.exportimport/actions/runs/13956151035/job/39067631154) for several Python versions. Error is for example:
```
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '3.4dev-r73107'
(package: zope.exceptions)
```
A slightly newer setuptools should help here.  But I try not to make a big version jump.
=> Try to fix CI.

CHANGES.rst, src/collective/exportimport/import_other.py
p.a.multilingual raises `KeyError` when translation is already linked 🤷🏼‍♂️
See https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/manager.py#L85
=> Fix when reimporting existing translations

base.cfg, requirements.txt
Use more recent zc.buildout and setuptools versions on Python 3.9+.
Sample [failure](https://github.com/collective/collective.exportimport/actions/runs/14313320340/job/40167791650#step:8:1178):
```
While:
Installing test.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
File "/home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/zc/buildout/buildout.py", line 2300, in main
getattr(buildout, command)(args)
File "/home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/zc/buildout/buildout.py", line 856, in install
installed_files = self[part]._call(recipe.install)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix CI again, for Plone 6.0.

CHANGES.rst, src/collective/exportimport/export_other.py
We investigated this issue in a Plone 4.3/dexterity multilanguage site. There were missing `relatedItems` relations on translated content items. Adding the index `Language="all"` fixed it.
I've also tried this change on a fresh 4.3 site without the `Language` index and it worked too. portal_catalog seems to ignore the keywords when there is no index.
=> Fix missing relations in `export_relations` on a multilanguage site
