src/collective/exportimport/configure.zcml
src/collective/exportimport/export_other.py
src/collective/exportimport/import_other.py
src/collective/exportimport/templates/export_content.pt
src/collective/exportimport/templates/import_content.pt
src/collective/exportimport/templates/import_defaultpages.pt
src/collective/exportimport/templates/import_localroles.pt
src/collective/exportimport/templates/import_members.pt
src/collective/exportimport/templates/import_ordering.pt
src/collective/exportimport/templates/import_relations.pt

Add export and import for default pages

---

src/collective/exportimport/configure.zcml
src/collective/exportimport/export_content.py
src/collective/exportimport/export_other.py
src/collective/exportimport/interfaces.py
src/collective/exportimport/serializer.py
src/collective/exportimport/templates/export_content.pt

Simplify handling migrations

---

CHANGES.rst
src/collective/exportimport/templates/export_content.pt

fix missing closing tag

---

CHANGES.rst
src/collective/exportimport/export_content.py
src/collective/exportimport/tests/test_export.py

Fix @id of collections and parents of subcollections

---

CHANGES.rst
src/collective/exportimport/configure.zcml
src/collective/exportimport/import_content.py
src/collective/exportimport/templates/links.pt

It uses the upgrade step from plone.app.querystring.
See #31 for details.

Add option to fix collection queries

---

src/collective/exportimport/import_other.py

Unescape html entities and line-breaks when importing comments

---

src/collective/exportimport/import_content.py
src/collective/exportimport/import_other.py
src/collective/exportimport/tests/test_export.py
src/collective/exportimport/tests/test_import.py

Includes datetime fixes from https://github.com/collective/collective.exportimport/commit/8d9739c3b9b5bfc5345a0f03b261eb7471764bf1

try to fix import in older versions

---

CHANGES.rst
src/collective/exportimport/export_other.py

Fix debug flag in ExportRelations

---

src/collective/exportimport/export_other.py

Display exception but continue exporting when there are unexportable objects

---

CHANGES.rst
src/collective/exportimport/import_other.py

Deserialize portlet-data using restapi to fix importing RichText

---

src/collective/exportimport/fix_html.py
src/collective/exportimport/tests/test_fix_html.py

Preserve links to browser-views by using a custom find_object

---

src/collective/exportimport/configure.zcml
src/collective/exportimport/deserializer.py
src/collective/exportimport/import_content.py
src/collective/exportimport/tests/test_import.py

Fix importing richtext with html entities

---

src/collective/exportimport/fix_html.py

beware we swallow errors in order to fix as many items as possible
some python2 compatibilty
sorry for black :/

Add more logging for html_fixer

---

src/collective/exportimport/export_content.py
src/collective/exportimport/import_content.py
src/collective/exportimport/tests/test_import.py

Export and import workflow_history

---

src/collective/exportimport/export_content.py
src/collective/exportimport/export_other.py

improve logging for export_discussion

Use catalog instead of ZopeFindAndApply 

---

setup.py

Pinn pyrsistent to a version below 1.16.0 for py2

---

CHANGES.rst
src/collective/exportimport/import_content.py

Fixes https://github.com/collective/collective.exportimport/issues/123

Fix AttributeError for getPhysicalPath when checking parent.

---

CHANGES.rst
README.rst
src/collective/exportimport/export_other.py
src/collective/exportimport/templates/export_other.pt
src/collective/exportimport/tests/test_export.py

Add option download_to_server to all exports

---

CHANGES.rst
src/collective/exportimport/fix_html.py

Also: remove duplicate method and improve readability

Add option to run custom html-fixers

---

src/collective/exportimport/fix_html.py
src/collective/exportimport/import_content.py

fix catchall in fix_html when there is no obj yet

---

requirements.txt
src/collective/exportimport/import_content.py
src/collective/exportimport/tests/test_drop_and_include.py
src/collective/exportimport/tests/test_export.py
src/collective/exportimport/tests/test_import.py

Add option to whitelist paths to import

Whitelist import paths

---

README.rst

Add pins from plone.restapi readme & add link

Document installing c.exportimport in Plone 4

---

requirements.txt
src/collective/exportimport/export_other.py
src/collective/exportimport/import_other.py
src/collective/exportimport/tests/test_export.py
src/collective/exportimport/tests/test_import.py

adding migration of localroles set on portal/siteroot level

Portal localroles

---

src/collective/exportimport/import_content.py

change log level from info to warn on non-existing parent and parent not folderish

change log level from info to warn on non-existing parent and parent not folderish

---

CHANGES.rst
src/collective/exportimport/fix_html.py
src/collective/exportimport/tests/test_fix_html.py

Only used when running @@fix_html in Plone 6.

Add fixer img_variant_fixer to set image-variants in html-fields 

---

CHANGES.rst
src/collective/exportimport/serializer.py

Fix the way we get a blob path

---

CHANGES.rst
src/collective/exportimport/serializer.py

* Better serialization if criteria: 
* use newer criteria added in Plone 5
* add fallback for some criteria
* Export sort_on and sort_reversed
* Export customView as tabular_view

Improve topic export

---

.github/workflows/tests.yml

Node.js 12 actions are deprecated.

update to latest versions

---

src/collective/exportimport/export_content.py
src/collective/exportimport/export_other.py
src/collective/exportimport/import_content.py

* allow passing custom filenames to exports
* support export and import of Plone Site object

Support for requirements of plone.distribution

---

CHANGES.rst
src/collective/exportimport/export_content.py
src/collective/exportimport/import_content.py

- refs #216
**Requires** https://github.com/plone/Products.CMFEditions/pull/101

Fix editing revision author

---

src/collective/exportimport/export_other.py

fixes issues introduced in #258

Use "unrestrictedSearchResults" for relation path queries
